# Generated by Django 4.1 on 2022-08-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('YOM', models.DateField(blank=True, null=True, verbose_name='Year Of Make')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('technical', models.TextField(blank=True, null=True, verbose_name='Technical')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Options')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millage', models.IntegerField(verbose_name='Millage')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='webapp.dealer')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='webapp.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='webapp.company'),
        ),
    ]
