# Generated by Django 4.1 on 2022-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='transmission',
            field=models.CharField(choices=[('Auto', 'Automatic'), ('Manual', 'Manual')], default='Auto', max_length=255, verbose_name='Transmission'),
        ),
    ]
