# Generated by Django 4.1 on 2022-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_model_vehicle_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='YOM',
            field=models.CharField(max_length=255, null=True, verbose_name='Year of Make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='millage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Millage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.CharField(max_length=255, null=True, verbose_name='Price'),
        ),
    ]
